name: CustomItemsSB
main: customitems/main
api: 3.0.0
author: secretsiver313
version: 1.0
description: "Custom Items
commands:
  hc:
    default: op
    permission: hc.use
    description: Gives you a Heart Crystal
